---
output: html_document
---

<h1 class="title">RcppNT2</h1>

RcppNT2 is an R package that provides bindings to the
[**Numerical Template Toolbox**](https://github.com/jfalcou/nt2)
(**NT<sup>2</sup>**). It provides a framework for implementing
highly optimizable algorithms, taking advantage of
[SIMD instructions](https://en.wikipedia.org/wiki/SIMD) when
possible, and falling back to scalar operations when not.

## Overview

**NT<sup>2</sup>** is an open source C++ library aimed at 
simplifying the development, debugging and optimization of 
high-performance computing applications by providing a 
Matlab-like syntax that eases the transition between 
prototype and actual application.

**NT<sup>2</sup>** provides with a large toolbox of
algorithms, facilitating scientific computing for many
tasks. By including `<RcppNT2.h>`, these
functions are all made available as part of the `nt2`
namespace, and so are immediately ready to use. A quick
glance at the types of functions available:

- **Arithmetic**: Most of the arithmetic operations you are familiar
                  with will be provided by **NT<sup>2</sup>**: as a
                  sampling, we have `sum()`, `prod()`, `abs()`, `floor()`,
                  `ceil()`, `sqrt()`, `sqr()` `exp()`, `pow()` and `log()`.

- **Bitwise**: Bitwise operators are provided in the `nt2`
               namespace, prefixed with `bitwise_`. For example,
               `nt2::bitwise_and()` can be used to perform the logical
               equivalent of the `&` operator. These functions also work
               with floating point types.

- **Trigonometric**: All of `sin()`, `cos()` and `tan()` are provided within
                     the `nt2` namespace, alongside their inverses `asin()`,
                     `acos()`, and `atan()`. The trigonometric inverses
                     (`sec()`, `csc()`, `cot()`) are provided as well.

The full collection can be browsed within the
[**NT<sup>2</sup>** User Manual](http://nt2.metascale.fr/doc/html/user_manual0.html) -- it's
worth taking a quick look at an overview for each toolset, to get
an idea of what functions are provided.

## Articles

The [Rcpp Gallery](http://gallery.rcpp.org/) hosts a number of stand-alone articles describing
how Rcpp and its various extensions can be used. A number of articles
introducing RcppNT2 are provided as well:

- [Introduction to RcppNT2](http://gallery.rcpp.org/articles/rcppnt2-introduction) --- Introduces **NT<sup>2</sup>**, RcppNT2, and shows how a vector sum could be computed using SIMD instructions.
- [Using RcppNT2 to Compute the Sum](http://gallery.rcpp.org/articles/rcppnt2-sum) --- Shows how RcppNT2, alongside `simdReduce()`, could be used to compute the sum of a sequence of numbers.
- [Using RcppNT2 to Compute the Variance](http://gallery.rcpp.org/articles/rcppnt2-variance) --- Shows how RcppNT2, alongside `simdFor()`, could be used to compute the variance of a sequence of numbers.

## Examples

RcppNT2 also comes with a number of standalone examples, which we hope
will help demonstrate how the package can be used. Try running the
examples yourself with `Rcpp::sourceCpp()`, and then iterate to
get a better feel for how RcppNT2 can be used.

- [Using simdTransform()](https://github.com/RcppCore/RcppNT2/blob/master/inst/examples/examples-transform.cpp) --- demonstrates how `simdTransform()` can be used to compute the vectorized addition of two vectors.

- [Using simdFor()](https://github.com/RcppCore/RcppNT2/blob/master/inst/examples/examples-for-each.cpp) --- demonstrates how `simdFor()` can be used, alongside a stateful functor, to compute the product of a set of numbers.

- [Variadic simdFor()](https://github.com/RcppCore/RcppNT2/blob/master/inst/examples/examples-variadic-for.cpp) --- demonstrates how the variadic flavor of `simdFor()` can be used to handle arbitrary number of vector inputs.

- [Handling Missing Values](https://github.com/RcppCore/RcppNT2/blob/master/inst/examples/example-na-handling-variance.cpp) --- demonstrates how missing values can be handled. The variance of a vector of numbers is computed, with missing values omitted.

After you've browsed through a couple examples, take a look at the
[Quick Reference](quick-reference.html) to learn more.

## Getting Started

You can install the RcppNT2 package from GitHub using devtools:

```r
devtools::install_github("RcppCore/RcppNT2")
```

If you're using RStudio, consider downloading the
[RStudio Preview](https://www.rstudio.com/products/rstudio/download/preview/)
first: the **NT<sup>2</sup>** library makes extensive use of
C++ template metaprogramming; unfortunately, this causes
huge slowdowns in the `libclang` diagnostics engine, which
powers the diagnostics behind C++ files open in RStudio. The
preview version adds some provisions to ensure this does not
happen.

### sourceCpp

Add the following to a standalone C++ source file to import RcppNT2:

```cpp
// [[Rcpp::depends(RcppNT2)]]
#include <RcppNT2.h>
```

When you compile a file using `Rcpp::sourceCpp()`, the
required compiler and linker settings for RcppNT2 will
be automatically included in the compilation.

Many of the optimizations underlying **NT<sup>2</sup>**
are made possible through the use of C++ template metaprogramming
techniques. As a consequence, it can often take a very long time
to compile translation units that include `<RcppNT2.h>`.

You can use `RcppNT2::precompileRcppNT2()` to generate a
[pre-compiled header](https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html),
which `Rcpp::sourceCpp()` will automatically include and use
as appropriate. This can improve compile times by up to ~5x
in translation units including the `<RcppNT2.h>` header.

### R Packages

Because RcppNT2 is a header-only library, using it in client
R packages is easy. Just ensure you have the following in your
`DESCRIPTION` file:

```yaml
LinkingTo: RcppNT2, BH (>= 1.60.0)
SystemRequirements: C++11
```

After you've added the above to the package you can simply
include the main RcppNT2 package header in source files that
need to use it:

```cpp
#include <RcppNT2.h>
```
